name: 'duckflix'
services:
    postgres:
        image: postgres:16-alpine
        container_name: duckflix_db
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PSWD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        networks:
            - duckflix_network
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
            interval: 5s
            timeout: 5s
            retries: 5

    rqbit:
        image: ikatson/rqbit:latest
        container_name: duckflix_rqbit
        restart: always

        ports:
            - '3030:3030' # API Port
            - '6881:6881/tcp' # Torrent ports
            - '6881:6881/udp'
        environment:
            - RQBIT_HTTP_LISTEN_ADDR=0.0.0.0:3030
        volumes:
            - rqbit_db:/home/rqbit/db
            - rqbit_cache:/home/rqbit/cache
            - ./data/temp/downloads:/home/rqbit/downloads
        networks:
            - duckflix_network

    backend:
        container_name: 'duckflix_backend'
        build:
            context: .
            dockerfile: packages/backend/Dockerfile
        restart: always
        init: true
        tty: true
        depends_on:
            postgres:
                condition: 'service_healthy'
        ports:
            - '3000:3000'
        env_file:
            - packages/backend/.docker.env
        environment:
            - NODE_ENV=production
        volumes:
            - ./data:/app/data
            - ./logs:/app/logs
            - ./certs:/app/certs:ro
        tmpfs:
            - /app/data/live:size=4G,mode=1777
        networks:
            - duckflix_network
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '3'
        # Hardware acceleration (optional)
        # Nvidia (NVENC)
        # Requires: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html
        # deploy:
        #     resources:
        #         reservations:
        #             devices:
        #                 - driver: nvidia
        #                   count: 1
        #                   capabilities: [gpu]

    frontend:
        container_name: duckflix_frontend
        build:
            context: .
            dockerfile: packages/frontend/Dockerfile
        env_file:
            - packages/frontend/.env
        restart: always
        ports:
            - '5173:80'

networks:
    duckflix_network:
        driver: bridge

volumes:
    postgres_data:
    rqbit_db:
    rqbit_cache:
